version: "3.8"

services:
  backend:
    build: ../backend
    ports:
      - "3050:3050"
    volumes:
      - ./backend:/app
    restart: always

  frontend:
    build: ../frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: always
